AWSTemplateFormatVersion: 2010-09-09
Description: My PHP Application
Transform: AWS::Serverless-2016-10-31
Resources:
  phpserver:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-phpserver
      Description: PHP Webserver
      CodeUri: src/php
      Runtime: provided
      Handler: index.php
      MemorySize: 3008
      Timeout: 30
      Tracing: Active
      Layers:
        #- !Sub arn:aws:lambda:${AWS::Region}:887080169480:layer:php73:3
        - !Sub arn:aws:lambda:ap-northeast-1:017033797206:layer:php73-layer-devel:5
      Events:
        api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
